---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress-mysql
  labels:
    app: wordpress
spec:
  template:
    spec:
      containers:
      - name: mysql
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: dev-secret
              key: dev-password
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: dev-secret
              key: dev-password
