---
apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: wordpress
  labels:
    app: wordpress
spec:
  template:
    spec:
      containers:
      - name: wordpress
        env:
        - name: WORDPRESS_DB_HOST
          value: dev-wordpress-mysql
        - name: WORDPRESS_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: dev-secret
              key: dev-password
  